useDotenv: true
service: mrs-replication-test-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  httpApi:
    cors: true
  environment:
    DATABASE_URL: ${env:DATABASE_URL}

functions:
  test:
    handler: v1/test.handler
    events:
      - httpApi:
          path: /test
          method: GET
  api:
    handler: v1/index.handler
    events:
      - httpApi:
          path: /
          method: GET
  read:
    handler: v1/read.handler
    events:
      - httpApi:
          path: /read
          method: GET
  create:
    handler: v1/create.handler
    events:
      - httpApi:
          path: /create
          method: POST
  delete:
    handler: v1/delete.handler
    events:
      - httpApi:
          path: /delete
          method: DELETE
